---

before_script:
  - VERSION=3.12.12 # TODO: setup ci to check python 10, 11 & 13
  - SUB_VERSION=$(echo ${VERSION} | sed 's/[0-9].\([0-9]*\).[0-9]*/\1/g')
  - source "$(ccc_home -W -u mpc)/pcvs_env/spack/share/spack/setup-env.sh"
  - spack env activate "pcvs_env_${SUB_VERSION}"
  - spack load "python@${VERSION}" sqlite@3.46.0 py-pysocks@1.7.1 py-setuptools py-wheel
  - source "$(ccc_home -W -u mpc)/pcvs_env/python_${SUB_VERSION}_venv/bin/activate"
  - export LD_LIBRARY_PATH="$(ccc_home -W -u mpc)/pcvs_env/libgit2/build/"
  # pre-commit setup:
  - export PATH=$PATH:"$(ccc_home -u mpc)/mpc_pre_commit/bin"
  - export PIP_FIND_LINKS="$(ccc_home -W -u mpc)/pcvs_env/python_${SUB_VERSION}_mirror"
  - export PIP_NO_INDEX=1
  - export PIP_NO_BUILD_ISOLATION=1


variables:
  GIT_CLEAN_FLAGS: -fddx -e .coverage

.scope: &scope
  only:
    - master
    - devel
    - merge_requests
    - web

stages:
#  - Installation
  - PCVS
  - Documentation
  - Deploy

# pcvs is installed for testing via tox, no need to install it.
#Install PCVS:
#    <<: *scope
#    stage: Installation
#    script:
#    - pip install '.[dev]'
#    - pcvs --version

Coverage PCVS:
  <<: *scope
  stage: PCVS
  script:
    # TODO: when tox is fixed on inti (tox>=4.21) use tox instead of duplicating test
    #- tox -e pcvs-coverage
    - module load mpi
    - coverage erase
    - coverage run --source=./pcvs -m pytest ./tests/pcvs
    - coverage report --precision=2 --fail-under=50 --sort=-miss

Lint PCVS:
  <<: *scope
  stage: PCVS
  script:
    # TODO: when tox is fixed on inti (tox>=4.21) use tox instead of duplicating test
    #- tox -e pcvs-lint
    - cd ${CI_PROJECT_DIR}
    - intify_pre_commit.sh .pre-commit-config.yaml
    - git add .pre-commit-config.yaml
    - git config --global --add safe.directory "$(ccc_home -u mpc)/mpc_pre_commit/pre_commit_hooks/pre-commit-hooks/.git"
    - pre-commit install --install-hooks
    - pre-commit run --all-files

Build Doc:
  <<: *scope
  stage: Documentation
  allow_failure: true
  script:
    # TODO: when tox is fixed on inti (tox>=4.21) use tox instead of duplicating test
    # - tox -e doc
    - cd docs
    # TODO: install sphinx>=8.2.23 with python>=12
    - make clean && make html

Lint Doc:
  <<: *scope
  stage: Documentation
  allow_failure: true
  script:
    # TODO: when tox is fixed on inti (tox>=4.21) use tox instead of duplicating
    # - tox -e doc-lint
    # TODO: install darglint on inti with spack organizer
    - darglint --verbosity=2 --ignore-regex=cli_.* pcvs

Test Doc:
  <<: *scope
  stage: Documentation
  allow_failure: true
  script:
    # TODO: when tox is fixed on inti (tox>=4.21) use tox instead of duplicating
    # - tox -e doc-coverage
    # TODO: install docstr-coverage on inti with spack organizer
    - docstr-coverage pcvs --fail-under 70

Deploy Doc:
  only:
    - devel
  pages: true
  stage: Deploy
  script:
    - cd docs && make html
  after_script:
    - mv docs/build/html/ ./public/
  artifacts:
    paths:
      - public
