#!/usr/bin/env bash

# setup proxy manually before launching

umask 007

mkdir -p pcvs_env

pushd pcvs_env

#git clone ssh://git@gitlab.ccc.ocre.cea.fr:9422/cea-mpc-team/pcvs && (
git clone https://github.com/cea-hpc/pcvs && (
	pushd pcvs
	#git switch "pcvs_1_0"
	git switch "devel"
)


git clone https://github.com/libgit2/libgit2 && (
	pushd libgit2
	git switch --detach "v1.7.2"
	mkdir build
	pushd build
	cmake ..
	cmake --build . --parallel 8
)

git clone --depth=2 https://github.com/spack/spack && (
	echo "    destination: $(realpath .)/spack_repos" >> spack/etc/spack/defaults/base/repos.yaml
)
source spack/share/spack/setup-env.sh

for v in "3.10.19" "3.11.14" "3.12.12" "3.13.11" # "3.14.0" TODO: add 3.14 support
do
	sub_ver=$(echo ${v} | sed 's/[0-9].\([0-9]*\).[0-9]*/\1/g')

	# setup spack env
	spack env create "pcvs_env_${sub_ver}"
	spack env activate "pcvs_env_${sub_ver}"
	spack add "sqlite@:3.46.0"
	spack add "python@${v}"
	spack add "py-pysocks@1.7.1"
	spack add "py-setuptools"
	spack add "py-wheel"
	spack install
	spack load "python@${v}" sqlite@3.46.0 py-pysocks@1.7.1 py-setuptools py-wheel

	# setup python env
	python -m venv "python_${sub_ver}_venv"
	source "python_${sub_ver}_venv/bin/activate"
	mkdir -p "python_${sub_ver}_mirror"
	pushd pcvs
	pip download '.[dev]' -d "../python_${sub_ver}_mirror"
	export C_INCLUDE_PATH="$(realpath ../libgit2/build/include/):$(realpath ../libgit2/include/)"
	export LIBRARY_PATH=$(realpath ../libgit2/build/) # add this path to LD_LIBRARY_PATH at runtime
	pip install '.[dev]' --find-links "../python_${sub_ver}_mirror" --no-index --no-build-isolation
	popd

	spack unload "python@${v}" sqlite@3.46.0 py-pysocks@1.7.1 py-setuptools py-wheel
	spack env deactivate
done

popd
